export const darkPrimary = '#303F9F'
export const lightPrimary = '#C5CAE9'
export const primary = '#3F51B5'
export const accent = '#FF5722'
export const primaryText = '#212121'
export const secondaryText = '#757575'
export const divider = '#BDBDBD'

export const white = '#FFFFFF'
export const green = '#388E3C'
export const red = '#D32F2F'
